[package]
name = "myproject"
version = "0.1.0"
authors = ["nickfarrow <nick@nickfarrow.com>"]
edition = "2021"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
#pio = ["esp-idf-sys/pio"]
default = ["native"]
native = ["esp-idf-sys/native"]

[dependencies]
esp-idf-sys = { version = "=0.31.5", features = ["binstart"] }
esp-idf-svc = { version="=0.42.1", features = ["experimental", "alloc"] }
esp32-c3-dkc02-bsc = { path = "/home/nick/repos/espressif-trainings/common/lib/esp32-c3-dkc02-bsc" }
schnorr_fun = { path = "/home/nick/repos/secp256kfun/schnorr_fun" }
secp256kfun = { path = "/home/nick/repos/secp256kfun/secp256kfun" }
# rand = "0.8.5"
rand = "0.8.4"
sha2 = "0.10"
rng = "0.1.0"
clightningrpc = "0.2.0"



[build-dependencies]
embuild = "0.28"
anyhow = "1"


# [profile.release]
# opt-level = "s"

# [profile.dev]
# debug = true # Symbols are nice and they don't increase the size on Flash
# opt-level = "z"

# [features]
# default = ["native"]
# native = ["esp-idf-sys/native"]

# [dependencies]
# esp-idf-sys = { version = "=0.31.5", features = ["binstart"] }
# esp-idf-svc = { version="=0.42.1", features = ["experimental", "alloc"] }
# esp32-c3-dkc02-bsc = { path = "../../common/lib/esp32-c3-dkc02-bsc" }
# log = "0.4"
# anyhow = "1"
# toml-cfg = "0.1"

# [build-dependencies]
# embuild = "0.28"
# anyhow = "1"
