[workspace]

members = [
    "frostsnap_core",
    "device",
    "frostsnap_coordinator",
    "frostsnap_comms",
    "frostsnapp/native",
]
resolver = "2"


[workspace.dependencies]
bincode = {  version = "2.0.0-rc.3", features = ["serde", "alloc", "derive"], default-features = false }
serde = { version = "1", features = ["derive","alloc"], default-features = false }
frostsnap_core = { path = "frostsnap_core", default-features = false }
frostsnap_comms = { path = "frostsnap_comms", default-features = false }
frostsnap_coordinator = { path = "frostsnap_coordinator" }
tracing = { version = "0.1", default-features = false }
llsdb = { git = "https://github.com/LLFourn/llsdb.git", rev = "b1540959897b098e7fea28799a377e210b365357" }
rand_chacha = { version = "0.3", default-features = false }
sha2 = { version = "0.10", default-features = false }


[patch.crates-io]
# bdk_chain = { path = "../bdk/crates/chain" }
bdk_chain = { git = "https://github.com/LLFourn/bdk.git", rev = "165f06b8f78bd24f57dfbfd66da1faa189c67457" }
bdk_electrum = { git = "https://github.com/LLFourn/bdk.git", rev = "165f06b8f78bd24f57dfbfd66da1faa189c67457" }
