[package]
name = "frostsnap_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = "0.6"
schnorr_fun = { path = "../../secp256kfun/schnorr_fun", features = ["alloc"] }
rand_chacha = "0.3"
sha2 = "0.10"
chacha20 = { version = "0.9", default-features = true }

[dev-dependencies]
rand = "0.8"
