[package]
name = "frostsnap_device"
version = "0.1.0"
authors = ["nickfarrow <nick@nickfarrow.com>"]
edition = "2021"

[features]
frostypede = ["air101", "air101-r2223", "rgb-led"]
ai-042c3 = ["rgb-led", "dep:display-interface", "dep:ssd1306"]
air101 = [
    "dep:display-interface-spi",
    "dep:mipidsi",
    "dep:embedded-graphics-framebuf",
]
# By default blue board uses air101-r225 but you can change it to r2223 with this flag
air101-r2223 = []
rgb-led = ["dep:esp-hal-smartled", "dep:smart-leds"]
mem_debug = []

[dependencies]
frostsnap_core = { workspace = true }
frostsnap_comms = { workspace = true }
hal = { package = "esp32c3-hal", version = "0.13.0" }
esp-alloc = "0.3.0"
esp-backtrace = { version = "0.9.0", features = [
    "esp32c3",
    "print-jtag-serial",
] }
esp-println = { version = "0.7.0", default-features = false, features = [
    "esp32c3",
    "jtag_serial",
] }
critical-section = "1.1.2"
nb = "1.1.0"
fugit = "0.3.7"
embedded-storage = "0.3.0"
esp-storage = { version = "0.3.0", features = ["esp32c3"] }
bincode = { workspace = true }
display-interface = { version = "0.4.1", optional = true }
ssd1306 = { version = "0.8", optional = true }
display-interface-spi = { version = "0.4.1", optional = true }
mipidsi = { version = "0.7.1", features = ["batch"], optional = true }
embedded-graphics-framebuf = { version = "0.5.0", optional = true }
embedded-graphics = "0.8.1"
embedded-text = "0.7.0"
esp-hal-smartled = { version = "0.6.0", features = [
    "esp32c3",
], optional = true }
smart-leds = { version = "0.3.0", optional = true }

[[bin]]
name = "frostypede"
required-features = ["frostypede"]
