[package]
name = "frostsnap_coordinator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
frostsnap_comms = { workspace = true }
frostsnap_core = { workspace = true, features = ["std", "rusqlite"] }
bincode = { workspace = true, features = ["std"] }
tracing = { workspace = true }
serialport = {version = "4.6", default-features = false } # default-features = false so no libudev
rand_core.workspace = true
rusqlite.workspace = true

bdk_chain = { version = "0.20" }
bdk_electrum = { version = "0.19", default-features = false, features = [
  "use-rustls-ring",
] }
bdk_coin_select = { version = "0.3" }
