name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  device:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ["v2"]
    defaults:
      run:
        working-directory: ./device
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@just
      - name: Setup | RISC-V GCC prerequisites
        run: sudo apt-get update && sudo apt-get install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build
      - name: Setup | RISCV GCC
        run: |
          wget -nv https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.05.24/riscv32-elf-ubuntu-22.04-nightly-2023.05.24-nightly.tar.gz
          tar -zxf riscv32-elf-ubuntu-22.04-nightly-2023.05.24-nightly.tar.gz
          echo "PATH=$PATH:${GITHUB_WORKSPACE}/device/riscv/bin" >> $GITHUB_ENV
          ls ${GITHUB_WORKSPACE}/device/riscv/bin
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imc-unknown-none-elf
          components: clippy
      - run: just lint-device --release
      - run: just build-device ${{ matrix.board }}
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: frostsnap-v2-${{ github.run_id }}.elf
          path: target/riscv32imc-unknown-none-elf/release/v2
          if-no-files-found: error

  non-device:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: sudo apt-get update
      - run: sudo apt-get install -y libudev-dev
      - run: just frostsnapp/install-rust-deps
      - run: just lint-non-device --release
      - run: just test --release --all-features

  app-build:
    name: Flutter app build
    runs-on: ubuntu-latest
    needs: device
    steps:
      - uses: actions/checkout@v3
      - name: Download firmwre elf
        uses: actions/download-artifact@v4
        with:
          name: frostsnap-v2-${{ github.run_id }}.elf
          path: target/riscv32imc-unknown-none-elf/release/
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android
      - uses: taiki-e/install-action@just
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 18
          cache: gradle
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
      - name: Show riscv release directory
        run: ls -R target/riscv32imc-unknown-none-elf/release/
      - run: sudo apt-get update && sudo apt install -y ninja-build libstdc++-12-dev libgtk-3-0 libgtk-3-dev libudev-dev
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - run: just frostsnapp/install-rust-deps
      - run: just frostsnapp/build linux
      - run: just frostsnapp/build appbundle

  flutter-analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    needs: device
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - name: Install flutter dependencies
        run: flutter pub get
        working-directory: ./frostsnapp
      - name: Run Flutter analyze
        run: |
          flutter analyze
